services:
  rust-app:
    build: .
    container_name: tv2_rust_backend
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
    networks:
      - tv2_backend_net
      - tv2_frontend_net
    depends_on:
      - mongodb
    restart: unless-stopped
